# Generated by Django 5.2.5 on 2025-09-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
